services:
  - type: web
    name: educational-token-display
    runtime: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
    healthCheckPath: /api/token-info
    plan: free
